name: CI Pipeline
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v4
      - name: 🔧 Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 🔐 Signin on Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: 🐳 Build & upload image on Docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gapalmasss/html_to_pdf:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}

  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v4
      - name: 🔍 Run SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
          SONAR_ORGANIZATION: "gapalmas-a7g-3k9m-zx2p-58d"
          SONAR_PROJECT_KEY: "gapalmas-a7g-3k9m-zx2p-58d_html_to_pdf"

  codeql-analysis:
    uses: gapalmas/github-actions-templates/.github/workflows/codeql-analysis.yml@main
    with:
      language: 'python'

  trivy-scan:
    needs: docker-build
    uses: gapalmas/github-actions-templates/.github/workflows/trivy-scan.yml@main
    with:
      image-name: 'gapalmasss/html_to_pdf'
      image-tag: 'latest'
      severity: 'CRITICAL,HIGH'
      output-format: 'sarif'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
